### ISSUE TITLE
建议增加对 algorithm 模块的 Python 支持

### ISSUE THREAD

**Issue by superfffire** [cv-rmvl/rmvl#141]
### 描述功能特点和出发点

建议增加对 algorithm 模块的 Python 支持

**Comment by zhaoxi-scut** [comment]
SWIG 对 C++11 以上的支持太有限了，RMVL 中大量的参数传递都使用的相关特性或者库，例如智能指针以及 `std::function`，后续极大概率会改成用 Pybind11 来实现，同时要满足

- CMake 在启用 `BUILD_PYTHON` 功能后，自动下载 Pybind11，即使用 `rmvl_download` CMake 函数
- 自动解析指定的头文件中需要转换成 Python 代码的 _部分_ ，这里需要转换的 **_部分_** 由特殊标识的宏来定义，比如 `RMVL_EXPORTS` 等，这一步计划通过使用 Python 脚本实现
- 解析得到的结果将直接作为 Pybind11 的绑定语句，这一步计划通过使用 Python 脚本实现

**Comment by zhaoxi-scut** [comment]
Python 和 Pybind11 的安装比较简单，暂时不使用 `rmvl_download` 来进行下载，后续可使用 RMVL GoogleTest 的管理方式，即找到系统中的 GoogleTest 时直接 `find_package`，未找到再下载
