### ISSUE TITLE
galaxy-sdk-suppot分支源码阅读时发现错误

### ISSUE THREAD

**Issue by drawal001** [cv-rmvl/rmvl#175]
### 系统配置信息

RMVL version：2.0

### 问题的详细描述

  我在阅读```galaxy-sdk-suppot```分支源码时发现```modules/camera/src/galaxy_camera/galaxy_camera.cpp```第132行：
```cpp
open_param.pszContent = const_cast<char *>(_id.c_str());
```
其中的```_id```参数之前并无数据传入，却给```open_param.pszContent```赋值，感觉存在一点问题，无实际复现代码。

### 复现步骤

```cpp
无
```

### 工单 Issue 提交清单

- [X] 我报告此代码中的 Bug，我能保证这不是我个人的疑问
- [X] 我在文档、未解决的 Issue 中检查了此问题，但没有找到任何解决方案
- [ ] 我尝试过更新到最新的 RMVL 版本，但问题仍然存在
- [ ] 我提供了此 Bug 相关的代码和数据文件（视频，图像等）

**Comment by zhaoxi-scut** [comment]
大概理解了你的问题，`_id` 的设置在构造函数中使用初始化列表进行了初始化的操作，具体的代码如下

```cpp
GalaxyCamera::Impl::Impl(CameraConfig config, std::string_view id) noexcept : _config(config), _id(id), _opened(open()) {}
```

不过 `id_info_map` 确实没有发挥出实际的作用，在其他厂商的相机 SDK 中，是通过使用 **相机信息结构体** 来打开相机的，这时需要存在一个 `std::string` 到 `/* 相机信息结构体 */` 的映射表。

而 GalaxySDK 中，打开相机并不需要传入该结构体，只需要传入对应的打开方式以及用于唯一标识相机的字符串，即代码中的 `_id`。目前计划的解决措施是，将 `std::unordered_map` 类型的 `id_info_map` 改为 `std::unordered_set`，仅在打开相机时判断当前传入的 `_id` 是否在该集合中。
